from __future__ import annotations

import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from app.models.candidate import CandidateConfiguration
from app.slicer.base import SlicerUnavailableError
from app.slicer.prusaslicer import PrusaSlicerService


def _candidate(**overrides) -> CandidateConfiguration:
    defaults = dict(run_id="run-1", layer_height=0.2, infill_percent=20, perimeter_count=3)
    defaults.update(overrides)
    return CandidateConfiguration(**defaults)


def test_slice_raises_when_binary_missing(tmp_path: Path) -> None:
    service = PrusaSlicerService(binary_path="definitely-not-a-real-binary-xyz")
    stl_path = tmp_path / "part.stl"
    stl_path.write_text("solid part\nendsolid part\n")

    with pytest.raises(SlicerUnavailableError):
        service.slice(stl_path, "generic_pla", _candidate())


def test_slice_reports_missing_stl_without_raising(tmp_path: Path) -> None:
    service = PrusaSlicerService(binary_path="definitely-not-a-real-binary-xyz")
    result = service.slice(tmp_path / "does-not-exist.stl", "generic_pla", _candidate())
    assert result.success is False
    assert "not found" in result.error


def test_build_command_includes_mvp_variables(tmp_path: Path) -> None:
    service = PrusaSlicerService()
    candidate = _candidate(
        layer_height=0.28,
        infill_percent=15,
        perimeter_count=4,
        supports_enabled=True,
        orientation_x=5,
        orientation_y=7,
        orientation_z=90,
    )

    command = service.build_command(
        stl_path=tmp_path / "part.stl",
        printer_profile="generic_pla",
        candidate_configuration=candidate,
        output_dir=tmp_path,
        binary_path="prusa-slicer",
    )

    assert "--layer-height" in command.argv
    assert "0.28" in command.argv
    assert "--perimeters" in command.argv
    assert "4" in command.argv
    assert "--support-material" in command.argv
    assert "--rotate-x" in command.argv
    assert "5.0" in command.argv
    assert "--rotate-y" in command.argv
    assert "7.0" in command.argv
    assert "--rotate" in command.argv
    assert "90.0" in command.argv
    assert "--export-gcode" in command.argv
    assert "--output" in command.argv


def test_build_command_fill_density_includes_percent_sign(tmp_path: Path) -> None:
    """Regression test: a bare number (no `%`) is silently reinterpreted by
    PrusaSlicer's legacy-config compatibility layer as an old-style 0..1
    fraction and multiplied by 100 (20 -> 2000%). Confirmed against
    PrintConfigDef::handle_legacy in PrintConfig.cpp — see module docstring
    in app/slicer/prusaslicer.py.
    """
    service = PrusaSlicerService()
    candidate = _candidate(infill_percent=20)

    command = service.build_command(
        stl_path=tmp_path / "part.stl",
        printer_profile="generic_pla",
        candidate_configuration=candidate,
        output_dir=tmp_path,
        binary_path="prusa-slicer",
    )

    fill_density_index = command.argv.index("--fill-density")
    assert command.argv[fill_density_index + 1] == "20%"


def test_build_command_omits_support_material_when_disabled(tmp_path: Path) -> None:
    service = PrusaSlicerService()
    candidate = _candidate(supports_enabled=False)

    command = service.build_command(
        stl_path=tmp_path / "part.stl",
        printer_profile="generic_pla",
        candidate_configuration=candidate,
        output_dir=tmp_path,
        binary_path="prusa-slicer",
    )

    assert "--support-material" not in command.argv


def test_build_command_omits_rotation_flags_when_zero(tmp_path: Path) -> None:
    service = PrusaSlicerService()
    candidate = _candidate(orientation_x=0, orientation_y=0, orientation_z=0)

    command = service.build_command(
        stl_path=tmp_path / "part.stl",
        printer_profile="generic_pla",
        candidate_configuration=candidate,
        output_dir=tmp_path,
        binary_path="prusa-slicer",
    )

    assert "--rotate-x" not in command.argv
    assert "--rotate-y" not in command.argv
    assert "--rotate" not in command.argv


def test_parse_print_time_seconds_from_typical_header() -> None:
    gcode = "; estimated printing time (normal mode) = 2h 25m 12s\n"
    assert PrusaSlicerService.parse_print_time_seconds(gcode) == 2 * 3600 + 25 * 60 + 12


def test_parse_print_time_prefers_total_over_first_layer_line() -> None:
    """Representative multi-line PrusaSlicer header: normal-mode total time,
    normal-mode first-layer time, and (if silent mode were enabled) a silent
    variant. Must pick the *total*, not the first-layer, time."""
    gcode = (
        "; generated by PrusaSlicer 2.7.0 on 2026-01-01 at 00:00:00\n"
        "; estimated printing time (normal mode) = 2h 25m 12s\n"
        "; estimated first layer printing time (normal mode) = 3m 40s\n"
        "; filament used [mm] = 1234.56\n"
        "; filament used [cm3] = 12.34\n"
        "; filament used [g] = 61.43\n"
    )
    assert PrusaSlicerService.parse_print_time_seconds(gcode) == 2 * 3600 + 25 * 60 + 12
    assert PrusaSlicerService.parse_filament_grams(gcode) == pytest.approx(61.43)


def test_parse_filament_grams_from_typical_header() -> None:
    gcode = "; filament used [g] = 61.43\n"
    assert PrusaSlicerService.parse_filament_grams(gcode) == pytest.approx(61.43)


def test_parse_functions_return_none_when_absent() -> None:
    gcode = "; no relevant metadata here\n"
    assert PrusaSlicerService.parse_print_time_seconds(gcode) is None
    assert PrusaSlicerService.parse_filament_grams(gcode) is None


# --- subprocess-mocked behavior (no real PrusaSlicer binary required) -----


def test_slice_returns_failure_on_nonzero_exit(tmp_path: Path) -> None:
    service = PrusaSlicerService(binary_path="prusa-slicer")
    stl_path = tmp_path / "part.stl"
    stl_path.write_text("solid part\nendsolid part\n")

    with (
        patch.object(PrusaSlicerService, "_resolve_binary", return_value="/fake/prusa-slicer"),
        patch(
            "subprocess.run",
            return_value=subprocess.CompletedProcess(args=[], returncode=1, stdout="", stderr="fatal: bad config"),
        ),
    ):
        result = service.slice(stl_path, "generic_pla", _candidate())

    assert result.success is False
    assert "bad config" in result.error


def test_slice_returns_failure_when_no_gcode_produced(tmp_path: Path) -> None:
    service = PrusaSlicerService(binary_path="prusa-slicer")
    stl_path = tmp_path / "part.stl"
    stl_path.write_text("solid part\nendsolid part\n")

    with (
        patch.object(PrusaSlicerService, "_resolve_binary", return_value="/fake/prusa-slicer"),
        patch(
            "subprocess.run",
            return_value=subprocess.CompletedProcess(args=[], returncode=0, stdout="ok", stderr=""),
        ),
    ):
        result = service.slice(stl_path, "generic_pla", _candidate())

    assert result.success is False
    assert "no G-code" in result.error


def test_slice_returns_failure_on_timeout(tmp_path: Path) -> None:
    service = PrusaSlicerService(binary_path="prusa-slicer", timeout_seconds=1)
    stl_path = tmp_path / "part.stl"
    stl_path.write_text("solid part\nendsolid part\n")

    with (
        patch.object(PrusaSlicerService, "_resolve_binary", return_value="/fake/prusa-slicer"),
        patch("subprocess.run", side_effect=subprocess.TimeoutExpired(cmd=["prusa-slicer"], timeout=1)),
    ):
        result = service.slice(stl_path, "generic_pla", _candidate())

    assert result.success is False
    assert "did not complete within" in result.error


def test_slice_parses_real_looking_gcode_end_to_end(tmp_path: Path) -> None:
    """Exercises the full slice() path against a mocked subprocess that
    writes a gcode file with representative header comments, proving the
    glob + read + parse plumbing works end to end without a real binary."""
    service = PrusaSlicerService(binary_path="prusa-slicer")
    stl_path = tmp_path / "part.stl"
    stl_path.write_text("solid part\nendsolid part\n")

    def fake_run(argv, cwd, **kwargs):
        output_index = argv.index("--output")
        gcode_path = Path(argv[output_index + 1])
        gcode_path.write_text(
            "; estimated printing time (normal mode) = 1h 2m 3s\n; filament used [g] = 15.5\n"
        )
        return subprocess.CompletedProcess(args=argv, returncode=0, stdout="Slicing result exported", stderr="")

    with (
        patch.object(PrusaSlicerService, "_resolve_binary", return_value="/fake/prusa-slicer"),
        patch("subprocess.run", side_effect=fake_run),
    ):
        result = service.slice(stl_path, "generic_pla", _candidate())

    assert result.success is True
    assert result.print_time_seconds == 3723
    assert result.filament_grams == pytest.approx(15.5)
    assert result.warnings == []
